// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v5.27.1
// source: transportService.proto

package transportService

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BusNumber struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Busnum int32 `protobuf:"varint,1,opt,name=busnum,proto3" json:"busnum,omitempty"`
}

func (x *BusNumber) Reset() {
	*x = BusNumber{}
	if protoimpl.UnsafeEnabled {
		mi := &file_transportService_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BusNumber) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BusNumber) ProtoMessage() {}

func (x *BusNumber) ProtoReflect() protoreflect.Message {
	mi := &file_transportService_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BusNumber.ProtoReflect.Descriptor instead.
func (*BusNumber) Descriptor() ([]byte, []int) {
	return file_transportService_proto_rawDescGZIP(), []int{0}
}

func (x *BusNumber) GetBusnum() int32 {
	if x != nil {
		return x.Busnum
	}
	return 0
}

type GetBusScheduleResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Busnum int32  `protobuf:"varint,1,opt,name=busnum,proto3" json:"busnum,omitempty"`
	Places string `protobuf:"bytes,2,opt,name=places,proto3" json:"places,omitempty"`
}

func (x *GetBusScheduleResponse) Reset() {
	*x = GetBusScheduleResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_transportService_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetBusScheduleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBusScheduleResponse) ProtoMessage() {}

func (x *GetBusScheduleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_transportService_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBusScheduleResponse.ProtoReflect.Descriptor instead.
func (*GetBusScheduleResponse) Descriptor() ([]byte, []int) {
	return file_transportService_proto_rawDescGZIP(), []int{1}
}

func (x *GetBusScheduleResponse) GetBusnum() int32 {
	if x != nil {
		return x.Busnum
	}
	return 0
}

func (x *GetBusScheduleResponse) GetPlaces() string {
	if x != nil {
		return x.Places
	}
	return ""
}

type TrackBusLocationResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Busnum   int32  `protobuf:"varint,1,opt,name=busnum,proto3" json:"busnum,omitempty"`
	Location string `protobuf:"bytes,2,opt,name=location,proto3" json:"location,omitempty"`
}

func (x *TrackBusLocationResponse) Reset() {
	*x = TrackBusLocationResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_transportService_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TrackBusLocationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrackBusLocationResponse) ProtoMessage() {}

func (x *TrackBusLocationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_transportService_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrackBusLocationResponse.ProtoReflect.Descriptor instead.
func (*TrackBusLocationResponse) Descriptor() ([]byte, []int) {
	return file_transportService_proto_rawDescGZIP(), []int{2}
}

func (x *TrackBusLocationResponse) GetBusnum() int32 {
	if x != nil {
		return x.Busnum
	}
	return 0
}

func (x *TrackBusLocationResponse) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

type ReportTrafficJamRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Busnum   int32  `protobuf:"varint,1,opt,name=busnum,proto3" json:"busnum,omitempty"`
	Feedback string `protobuf:"bytes,2,opt,name=feedback,proto3" json:"feedback,omitempty"`
}

func (x *ReportTrafficJamRequest) Reset() {
	*x = ReportTrafficJamRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_transportService_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReportTrafficJamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportTrafficJamRequest) ProtoMessage() {}

func (x *ReportTrafficJamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transportService_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportTrafficJamRequest.ProtoReflect.Descriptor instead.
func (*ReportTrafficJamRequest) Descriptor() ([]byte, []int) {
	return file_transportService_proto_rawDescGZIP(), []int{3}
}

func (x *ReportTrafficJamRequest) GetBusnum() int32 {
	if x != nil {
		return x.Busnum
	}
	return 0
}

func (x *ReportTrafficJamRequest) GetFeedback() string {
	if x != nil {
		return x.Feedback
	}
	return ""
}

type ReportTrafficJamResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Isaccepted bool `protobuf:"varint,1,opt,name=isaccepted,proto3" json:"isaccepted,omitempty"`
}

func (x *ReportTrafficJamResponse) Reset() {
	*x = ReportTrafficJamResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_transportService_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReportTrafficJamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportTrafficJamResponse) ProtoMessage() {}

func (x *ReportTrafficJamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_transportService_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportTrafficJamResponse.ProtoReflect.Descriptor instead.
func (*ReportTrafficJamResponse) Descriptor() ([]byte, []int) {
	return file_transportService_proto_rawDescGZIP(), []int{4}
}

func (x *ReportTrafficJamResponse) GetIsaccepted() bool {
	if x != nil {
		return x.Isaccepted
	}
	return false
}

var File_transportService_proto protoreflect.FileDescriptor

var file_transportService_proto_rawDesc = []byte{
	0x0a, 0x16, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x70, 0x6f, 0x72, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x10, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x70,
	0x6f, 0x72, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x22, 0x23, 0x0a, 0x09, 0x42, 0x75,
	0x73, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x62, 0x75, 0x73, 0x6e, 0x75,
	0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x62, 0x75, 0x73, 0x6e, 0x75, 0x6d, 0x22,
	0x48, 0x0a, 0x16, 0x47, 0x65, 0x74, 0x42, 0x75, 0x73, 0x53, 0x63, 0x68, 0x65, 0x64, 0x75, 0x6c,
	0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x62, 0x75, 0x73,
	0x6e, 0x75, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x62, 0x75, 0x73, 0x6e, 0x75,
	0x6d, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x73, 0x22, 0x4e, 0x0a, 0x18, 0x54, 0x72, 0x61,
	0x63, 0x6b, 0x42, 0x75, 0x73, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x62, 0x75, 0x73, 0x6e, 0x75, 0x6d, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x62, 0x75, 0x73, 0x6e, 0x75, 0x6d, 0x12, 0x1a, 0x0a,
	0x08, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x4d, 0x0a, 0x17, 0x52, 0x65, 0x70,
	0x6f, 0x72, 0x74, 0x54, 0x72, 0x61, 0x66, 0x66, 0x69, 0x63, 0x4a, 0x61, 0x6d, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x62, 0x75, 0x73, 0x6e, 0x75, 0x6d, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x62, 0x75, 0x73, 0x6e, 0x75, 0x6d, 0x12, 0x1a, 0x0a, 0x08,
	0x66, 0x65, 0x65, 0x64, 0x62, 0x61, 0x63, 0x6b, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x66, 0x65, 0x65, 0x64, 0x62, 0x61, 0x63, 0x6b, 0x22, 0x3a, 0x0a, 0x18, 0x52, 0x65, 0x70, 0x6f,
	0x72, 0x74, 0x54, 0x72, 0x61, 0x66, 0x66, 0x69, 0x63, 0x4a, 0x61, 0x6d, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x69, 0x73, 0x61, 0x63, 0x63, 0x65, 0x70, 0x74,
	0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0a, 0x69, 0x73, 0x61, 0x63, 0x63, 0x65,
	0x70, 0x74, 0x65, 0x64, 0x32, 0xb9, 0x02, 0x0a, 0x10, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x70, 0x6f,
	0x72, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x59, 0x0a, 0x0e, 0x47, 0x65, 0x74,
	0x42, 0x75, 0x73, 0x53, 0x63, 0x68, 0x65, 0x64, 0x75, 0x6c, 0x65, 0x12, 0x1b, 0x2e, 0x74, 0x72,
	0x61, 0x6e, 0x73, 0x70, 0x6f, 0x72, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x42,
	0x75, 0x73, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x1a, 0x28, 0x2e, 0x74, 0x72, 0x61, 0x6e, 0x73,
	0x70, 0x6f, 0x72, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x47, 0x65, 0x74, 0x42,
	0x75, 0x73, 0x53, 0x63, 0x68, 0x65, 0x64, 0x75, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x00, 0x12, 0x5d, 0x0a, 0x10, 0x54, 0x72, 0x61, 0x63, 0x6b, 0x42, 0x75, 0x73,
	0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1b, 0x2e, 0x74, 0x72, 0x61, 0x6e, 0x73,
	0x70, 0x6f, 0x72, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x42, 0x75, 0x73, 0x4e,
	0x75, 0x6d, 0x62, 0x65, 0x72, 0x1a, 0x2a, 0x2e, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x70, 0x6f, 0x72,
	0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x54, 0x72, 0x61, 0x63, 0x6b, 0x42, 0x75,
	0x73, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x00, 0x12, 0x6b, 0x0a, 0x10, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x54, 0x72, 0x61,
	0x66, 0x66, 0x69, 0x63, 0x4a, 0x61, 0x6d, 0x12, 0x29, 0x2e, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x70,
	0x6f, 0x72, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x52, 0x65, 0x70, 0x6f, 0x72,
	0x74, 0x54, 0x72, 0x61, 0x66, 0x66, 0x69, 0x63, 0x4a, 0x61, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x2a, 0x2e, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x70, 0x6f, 0x72, 0x74, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x54, 0x72, 0x61, 0x66,
	0x66, 0x69, 0x63, 0x4a, 0x61, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00,
	0x42, 0x1c, 0x5a, 0x1a, 0x67, 0x65, 0x6e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x74, 0x72, 0x61,
	0x6e, 0x73, 0x70, 0x6f, 0x72, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_transportService_proto_rawDescOnce sync.Once
	file_transportService_proto_rawDescData = file_transportService_proto_rawDesc
)

func file_transportService_proto_rawDescGZIP() []byte {
	file_transportService_proto_rawDescOnce.Do(func() {
		file_transportService_proto_rawDescData = protoimpl.X.CompressGZIP(file_transportService_proto_rawDescData)
	})
	return file_transportService_proto_rawDescData
}

var file_transportService_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_transportService_proto_goTypes = []interface{}{
	(*BusNumber)(nil),                // 0: transportService.BusNumber
	(*GetBusScheduleResponse)(nil),   // 1: transportService.GetBusScheduleResponse
	(*TrackBusLocationResponse)(nil), // 2: transportService.TrackBusLocationResponse
	(*ReportTrafficJamRequest)(nil),  // 3: transportService.ReportTrafficJamRequest
	(*ReportTrafficJamResponse)(nil), // 4: transportService.ReportTrafficJamResponse
}
var file_transportService_proto_depIdxs = []int32{
	0, // 0: transportService.TransportService.GetBusSchedule:input_type -> transportService.BusNumber
	0, // 1: transportService.TransportService.TrackBusLocation:input_type -> transportService.BusNumber
	3, // 2: transportService.TransportService.ReportTrafficJam:input_type -> transportService.ReportTrafficJamRequest
	1, // 3: transportService.TransportService.GetBusSchedule:output_type -> transportService.GetBusScheduleResponse
	2, // 4: transportService.TransportService.TrackBusLocation:output_type -> transportService.TrackBusLocationResponse
	4, // 5: transportService.TransportService.ReportTrafficJam:output_type -> transportService.ReportTrafficJamResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_transportService_proto_init() }
func file_transportService_proto_init() {
	if File_transportService_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_transportService_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BusNumber); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_transportService_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetBusScheduleResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_transportService_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TrackBusLocationResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_transportService_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReportTrafficJamRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_transportService_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReportTrafficJamResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_transportService_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_transportService_proto_goTypes,
		DependencyIndexes: file_transportService_proto_depIdxs,
		MessageInfos:      file_transportService_proto_msgTypes,
	}.Build()
	File_transportService_proto = out.File
	file_transportService_proto_rawDesc = nil
	file_transportService_proto_goTypes = nil
	file_transportService_proto_depIdxs = nil
}
