CREATE TABLE Users (
    Id VARCHAR(255) PRIMARY KEY,
    First_name VARCHAR(255),
    Last_name VARCHAR(255),
    Gender VARCHAR(50),
    Nation VARCHAR(255),
    Field VARCHAR(255),
    Parent_name VARCHAR(255),
    City VARCHAR(255),
    Age INT
);


INSERT INTO Users (Id, First_name, Last_name, Gender, Nation, Field, Parent_name, City, Age) VALUES
('1', 'John', 'Doe', 'Male', 'USA', 'Engineering', 'Jane Doe', 'New York', 28),
('2', 'Jane', 'Smith', 'Female', 'Canada', 'Medicine', 'John Smith', 'Toronto', 32),
('3', 'Emily', 'Jones', 'Female', 'UK', 'Literature', 'Anna Jones', 'London', 24),
('4', 'Michael', 'Brown', 'Male', 'Australia', 'Physics', 'James Brown', 'Sydney', 45),
('5', 'Jessica', 'Davis', 'Female', 'USA', 'Mathematics', 'Sarah Davis', 'Los Angeles', 30),
('6', 'David', 'Miller', 'Male', 'Germany', 'Chemistry', 'Susan Miller', 'Berlin', 38),
('7', 'Sarah', 'Wilson', 'Female', 'France', 'Biology', 'Robert Wilson', 'Paris', 27),
('8', 'Chris', 'Moore', 'Male', 'Italy', 'Computer Science', 'Nancy Moore', 'Rome', 33),
('9', 'Laura', 'Taylor', 'Female', 'Spain', 'Economics', 'George Taylor', 'Madrid', 29),
('10', 'James', 'Anderson', 'Male', 'USA', 'History', 'Alice Anderson', 'Chicago', 41),
('11', 'Linda', 'Thomas', 'Female', 'Mexico', 'Geography', 'Thomas Thomas', 'Mexico City', 36),
('12', 'Daniel', 'Jackson', 'Male', 'Brazil', 'Political Science', 'Martha Jackson', 'Sao Paulo', 34),
('13', 'Karen', 'White', 'Female', 'Argentina', 'Philosophy', 'Paul White', 'Buenos Aires', 26),
('14', 'Brian', 'Harris', 'Male', 'South Africa', 'Sociology', 'Donna Harris', 'Cape Town', 39),
('15', 'Betty', 'Martin', 'Female', 'Russia', 'Psychology', 'Peter Martin', 'Moscow', 31),
('16', 'Kevin', 'Lee', 'Male', 'China', 'Linguistics', 'Mary Lee', 'Beijing', 37),
('17', 'Donna', 'Walker', 'Female', 'Japan', 'Anthropology', 'Charles Walker', 'Tokyo', 28),
('18', 'Edward', 'Hall', 'Male', 'India', 'Law', 'Betty Hall', 'Mumbai', 40),
('19', 'Helen', 'Allen', 'Female', 'Pakistan', 'Art', 'Steven Allen', 'Karachi', 23),
('20', 'Jason', 'Young', 'Male', 'Bangladesh', 'Music', 'Patricia Young', 'Dhaka', 25),
('21', 'Amy', 'King', 'Female', 'Nigeria', 'Theology', 'Henry King', 'Lagos', 32),
('22', 'Jerry', 'Wright', 'Male', 'Egypt', 'Archaeology', 'Lisa Wright', 'Cairo', 29),
('23', 'Rebecca', 'Lopez', 'Female', 'Turkey', 'Architecture', 'Arthur Lopez', 'Istanbul', 33),
('24', 'Joshua', 'Hill', 'Male', 'South Korea', 'Astronomy', 'Megan Hill', 'Seoul', 36),
('25', 'Megan', 'Scott', 'Female', 'Malaysia', 'Statistics', 'Andrew Scott', 'Kuala Lumpur', 30),
('26', 'Andrew', 'Green', 'Male', 'Indonesia', 'Engineering', 'Diane Green', 'Jakarta', 28),
('27', 'Melissa', 'Adams', 'Female', 'Vietnam', 'Medicine', 'Brian Adams', 'Hanoi', 27),
('28', 'Stephen', 'Baker', 'Male', 'Philippines', 'Literature', 'Teresa Baker', 'Manila', 35),
('29', 'Patricia', 'Gonzalez', 'Female', 'Thailand', 'Physics', 'Frank Gonzalez', 'Bangkok', 41),
('30', 'George', 'Nelson', 'Male', 'Iran', 'Mathematics', 'Margaret Nelson', 'Tehran', 39),
('31', 'Dorothy', 'Carter', 'Female', 'Iraq', 'Chemistry', 'Joseph Carter', 'Baghdad', 34),
('32', 'Kenneth', 'Mitchell', 'Male', 'Afghanistan', 'Biology', 'Barbara Mitchell', 'Kabul', 38),
('33', 'Ashley', 'Perez', 'Female', 'Syria', 'Computer Science', 'Donald Perez', 'Damascus', 25),
('34', 'Paul', 'Roberts', 'Male', 'Saudi Arabia', 'Economics', 'Laura Roberts', 'Riyadh', 29),
('35', 'Deborah', 'Turner', 'Female', 'Yemen', 'History', 'Edward Turner', 'Sana', 31),
('36', 'Larry', 'Phillips', 'Male', 'Jordan', 'Geography', 'Rebecca Phillips', 'Amman', 37),
('37', 'Lisa', 'Campbell', 'Female', 'Lebanon', 'Political Science', 'Kenneth Campbell', 'Beirut', 28),
('38', 'Mark', 'Parker', 'Male', 'Israel', 'Philosophy', 'Stephanie Parker', 'Jerusalem', 32),
('39', 'Sandra', 'Evans', 'Female', 'Palestine', 'Sociology', 'Anthony Evans', 'Ramallah', 36),
('40', 'Donald', 'Edwards', 'Male', 'Kuwait', 'Psychology', 'Shirley Edwards', 'Kuwait City', 30),
('41', 'Michelle', 'Collins', 'Female', 'Qatar', 'Linguistics', 'Jeffrey Collins', 'Doha', 27),
('42', 'Charles', 'Stewart', 'Male', 'Bahrain', 'Anthropology', 'Gloria Stewart', 'Manama', 35),
('43', 'Emily', 'Sanchez', 'Female', 'Oman', 'Law', 'Bruce Sanchez', 'Muscat', 33),
('44', 'Joseph', 'Morris', 'Male', 'United Arab Emirates', 'Art', 'Ruth Morris', 'Abu Dhabi', 28),
('45', 'Laura', 'Rogers', 'Female', 'Sri Lanka', 'Music', 'Gerald Rogers', 'Colombo', 31),
('46', 'Matthew', 'Reed', 'Male', 'Nepal', 'Theology', 'Helen Reed', 'Kathmandu', 29),
('47', 'Nancy', 'Cook', 'Female', 'Bhutan', 'Archaeology', 'Roger Cook', 'Thimphu', 30),
('48', 'Frank', 'Morgan', 'Male', 'Maldives', 'Architecture', 'Carol Morgan', 'Malé', 34),
('49', 'Sharon', 'Bell', 'Female', 'Singapore', 'Astronomy', 'Walter Bell', 'Singapore', 37),
('50', 'Gary', 'Murphy', 'Male', 'New Zealand', 'Statistics', 'Janet Murphy', 'Wellington', 39);
